### ISSUE TITLE
atomic XRP

### ISSUE THREAD

**Issue by antiarmxr** [ebellocchia/bip_utils#111]
what about XRP atomic wallet derevation path?

send example pls.

**Comment by ebellocchia** [comment]
The [Atomic page](https://support.atomicwallet.io/article/146-list-of-derivation-paths) states `m/44'/144'/0'/0/0`, which is the standard one, but apparently the generated address is different. So, I suppose we should make some tests to get what the wallet is actually doing.

**Comment by ebellocchia** [comment]
Hi,
Atomic does things differently for some coins and unfortunaltely it's not documented how, so it's hard to understand how to get the same addresses sometimes.

**Comment by oseed15** [comment]
Hi, any ideas for atomic ?

**Comment by Codebyethan40** [comment]
@oseed15 Thanks for getting in touch! If you need any further support, feel free to email us at interact.gitresponse@gmail.com. We're happy to assist!

**Comment by jimtje** [comment]
In case this is still an issue for anyone, what happened was that during the step of turning a seed into a private key and chaincode, some developer had chosen the wrong half of the 64 byte hexstring and so, ended up deriving everything from the chaincode and not the private key. This really can only be a dev mistake so I did not submit a pull request but I have a PoC posted among my repos for XRP only. I have not looked into other coins since, frankly, the XRP issue seems to be the most prominent, but it would not surprise me that it's the same sort of sloppiness in its early days persisting, since I was actively looking for backdoors and found none in the supposed "infected" apk or any other. The libraries they use are off the shelf NPM pulls once you reconstruct it but unwebpacking them. Later they obfuscated the names but wakaru and webcrack are both more than sufficient in reconstructing pretty much the entire cordova package anyway.

This might be one of a few legit "fat fingers" momednt that ended up having some tangible consequences, but ultimately, I mean, 35 mil in what was certainly a pretty amateurish effort on chain is meh enough for the feds to handwave so, shrug. But yeah, put the chaincode in and see.
