### ISSUE TITLE
scalecodec comes with requests as a dependency

### ISSUE THREAD

**Issue by damascene** [ebellocchia/bip_utils#66]
bip_utils doesn't connect to network however `scalecodec` which is related to Palkdot is installing `requests` library. It's included in `requirements.txt` 

Hopefully there would be a way to make `scalecodec` as an optional dependency.  Seems like `bip_utils` comes with about 20 dependencies. Would you consider documenting which libraries is needed for which functionality. 

thank you.

```
$ poetry show --tree py-crypto-hd-wallet
py-crypto-hd-wallet 1.1.0 HD (Hierarchical Deterministic) wallet for cryptocurrencies based on bip_utils library
└── bip-utils >=2.3,<3.0
    ├── coincurve >=15.0.1,<18.0.0 
    │   ├── asn1crypto * 
    │   └── cffi >=1.3.0 
    │       └── pycparser * 
    ├── crcmod >=1.7,<2.0 
    ├── ecdsa >=0.15,<1.0 
    │   └── six >=1.9.0 
    ├── ed25519-blake2b >=1.4,<2.0 
    ├── py-sr25519-bindings >=0.1.3,<2.0.0 
    ├── pycryptodome >=3.6,<4.0 
    ├── pynacl >=1.1,<2.0 
    │   └── cffi >=1.4.1 (circular dependency aborted here)
    ├── scalecodec >=1.0,<2.0 
    │   ├── base58 >=2.0.1 
    │   ├── more-itertools * 
    │   └── requests >=2.24.0 
    │       ├── certifi >=2017.4.17 
    │       ├── charset-normalizer >=2.0.0,<2.1.0 
    │       ├── idna >=2.5,<4 
    │       └── urllib3 >=1.21.1,<1.27 
    └── six >=1.12.0 (circular dependency aborted here)
```

**Comment by ebellocchia** [comment]
Hi,
the list of dependencies is listed at the beginning of the readme with the related explanation:
- [crcmod](https://pypi.org/project/crcmod/) for CRC computation
- [pycryptodome](https://pypi.org/project/pycryptodome/) for cryptographic functions
- [coincurve](https://pypi.org/project/coincurve/) for secp256k1 curve
- [ecdsa](https://pypi.org/project/ecdsa/) for nist256p1 and secp256k1 curves
- [ed25519-blake2b](https://pypi.org/project/ed25519-blake2b/) for ed25519-blake2b curve
- [pynacl](https://pypi.org/project/PyNaCl/) for ed25519 curve
- [py-sr25519-bindings](https://pypi.org/project/py-sr25519-bindings/) for sr25519 curve
- [scalecodec](https://pypi.org/project/scalecodec/) for SCALE encoding

I don't think there is anything useless. Beside `scalecodec`, it's all stuff needed for cryptography. I implemented most of the stuff by myself just to minimize the usage of external libraries (e.g. base58, bech32, ss58, all the mnemonics part).
Anyway, yes I could implement the SCALE encoding by myself as well, since I only need a small subset of it. I'll consider doing it.

Regards,
Emanuele
