### ISSUE TITLE
Signature verification

### ISSUE THREAD

**Issue by aleixisp** [ebellocchia/bip_utils#77]
I see this module is quite completed and provides many capabilities <round a lot of different blockchains, I'm trying to find a module which allows verifying various signatures from different chains, I'm aware in all of them the signature verification is using EDCSA

I would like to know if this module allows for signature verification given the message, Signature and Publickey?

If so, could you point to the appropriate resource within the module?

Many thanks,
Aleix

**Comment by ebellocchia** [comment]
Hi,
nope. When I wrote the ecc module, I didn't add methods for signature signing/verification because I thought they were outside the scope of the library. They could be added of course, but for now you can only use the external ecc libraries that are installed as dependencies and do it manually.

Regards,
Emanuele

**Comment by FrankC01** [comment]
@aleixisp Wondering what you ended up doing for signing/verifications?
