### ISSUE TITLE
Include Solana within accepted wallet addresses

### ISSUE THREAD

**Issue by aleixisp** [ebellocchia/bip_utils#9]
Hey,

This package is a super nice work. I have this suggestions, to see if you thinks it's possible to implement :)
Thanks for this awesome package.

Regards,
Aleix López

**Comment by ebellocchia** [comment]
Yes absolutely, I'm studying how to add Polkadot and Solana.
The problem is that they use different elliptic curves and the BIP32 derivation scheme is totally different, so it's much harder to add them with respect to coins that follow Bitcoin derivation scheme. I'm trying to find a way to integrate the new scheme nicely without breaking the class hierarchy.
