### ISSUE TITLE
Custom derivative path for new coins (ex. APTOS)

### ISSUE THREAD

**Issue by Viatina** [ebellocchia/bip_utils#91]
Hello! In documentation you provide huge list of applyed coins and their derivatives paths, but when new block chain and their coins appear, we need to have opportunity work with them.

Unfortunatly, I can't find any suggestions with **custom** derivative path for creating wallets key pairs, for example new one - **m/44'/637'/0'/0'/0' (APTOS)**

    # Construct from seed
    bip44_mst_ctx = Bip44.FromSeed(seed_bytes, Bip44Coins.ALGORAND)
    # Print master key
    print(f"Master key (bytes): {bip44_mst_ctx.PrivateKey().Raw().ToHex()}")
    print(f"Master key (extended): {bip44_mst_ctx.PrivateKey().ToExtended()}")
    print(f"Master key (WIF): {bip44_mst_ctx.PrivateKey().ToWif()}")

    # Derive BIP44 account keys: m/44'/0'/0'
    bip44_acc_ctx = bip44_mst_ctx.Purpose().Coin().Account(0)
    # Derive BIP44 chain keys:  m/44'/0'/0'/0
    bip44_chg_ctx = bip44_acc_ctx.Change(Bip44Changes.CHAIN_EXT)

You provide examples code in lib, but I trying append some custom coins in **Bip44Coins**, what didn't change anything, I can't create my own custom path.
Please, can you explain how we can use our own custom path for new blockchain and their coins?

Also, I understand maybe you are a busy and haven't enough time to append new coins path to your code, so I believe this answer avoid similar questions in future_

**Comment by ebellocchia** [comment]
Hi,
Sorry for the late answer.
I can add new coins to the lib if requested, as far as it is supported by the existent ECC libs, it's not a problem.

Anyway, I try to summarize how to do that. Here I assume that the coin is based on an elliptic curve that is already supported by the lib, otherwise it should be added and it's not an easy job.

1. First of all, you have to determine the algorithm used by the coin to encode the public key to address. If the algorithm is already implemented by the lib, then you are lucky and you can move to the next step. Otherwise, you have to search and understand how the algorithm works and implement it, by writing an encoder and a decoder class in the `bip_utils\addr` folder.
2. Add the generic coin configuration in `bip_utils\coin_conf\coins_conf.py`, like the coin name and acronym and any other constants that could be useful.
3. Add the new coin enum in `bip_utils\bip\conf\bip44\bip44_coins.py`
4. Add the new coin configuration in `bip_utils\bip\conf\bip44\bip44_conf.py`. The `coin_idx` value is the second index of the derivation path (as defined by BIP44), so that's what you use to define the specific path for the coin. Usually I add the index in the `bip_utils\slip\slip44\slip44.py` to keep everything tidy, but you can also just write the integer value. The `bip32_cls` value defines the derivation scheme used by the coin. The `addr_cls` value is the address encoder class used by the coin.
5. Associate the coin enum with the coin configuration in `bip_utils\bip\conf\bip44\bip44_conf_getter.py` by adding a new entry to the `COIN_TO_CONF` dictionary.
6. You are done, you should be able to use the new coin with the `Bip44` class (of course, if the coin uses a different BIP like BIP49, just use the correspondent files and class).
7. Finally, I always add related tests for the coin in `tests\bip\bip44\test_bip44.py` and I create new tests for the address encoding/decoding classes (if any) in the `tests\addr` folder. This is for completeness, it is not required if you want to make it work quickly.

I hope it's clear.

Regards,
Emanuele
