### ISSUE TITLE
How to derive address using bip_32_ctx

### ISSUE THREAD

**Issue by Anynomouss** [ebellocchia/bip_utils#96]
**Feature Request, add 'ToAddress()' to Bip32Slip10Secp256k1**
BIP44, BIP49 and BIP84 objects all  allow you to convert a public key to address as shown in the example below.:

```
## derive at root level
bip44_addr_ctx.PublicKey().ToAddress()
## derive at account level
bip44_acc_ctx = bip44_mst_ctx.Purpose().Coin().Account(0)
## derive at change level
bip44_chg_ctx = bip44_acc_ctx.Change(Bip44Changes.CHAIN_EXT)
## derive at index level
bip44_addr_ctx = bip44_chg_ctx.AddressIndex(0)
## get addres a i=0
address = bip44_addr_ctx.PublicKey().ToAddress()
```
Would it be possible to add the same function to a BIP32 object? 
If I remember correctly, in the past there was a BIP32 class just like there is now for BIP44, BIP49 and BIP84. The BIP32 class did did have a build in ToAddress() function. Not sure why this was removed. So what I would like to be able to do is:
```
bip32_ctx = Bip32Slip10Secp256k1.FromSeedAndPath(seed_bytes, "m/0'/0'/0")
bip32_ctx.PublicKey().ToAddress()
```
If there is another simple way to go from Public key to address using bib_utils for a BIP32 object, please let me know. Also it might be handy to add an example of it to:
https://github.com/ebellocchia/bip_utils/blob/master/readme/bip32.md

**Comment by Anynomouss** [comment]
Solved it for the moment using Peter Todd's bitcoin lib, but would still be nice to do it without an extra dependency.
`
import bitcoin
#address = bitcoin.pubkey_to_address(public_key)
            address = bitcoin.pubkey_to_address(bip32_ctx_address.PublicKey().RawCompressed().ToHex())`

**Comment by ebellocchia** [comment]
Hi,
you don't need any external library. You have all the address classes for encoding the public key, like shown in the [BIP32 examples](https://github.com/ebellocchia/bip_utils/tree/master/examples) and the [related doc](https://github.com/ebellocchia/bip_utils/blob/master/readme/utility/addr.md), e.g.:

`btc_addr = P2PKHAddrEncoder.EncodeKey(bip32_ctx.PublicKey().KeyObject(), net_ver=b"\x00")`
`eth_addr = EthAddrEncoder.EncodeKey(bip32_ctx.PublicKey().KeyObject())`

The reason why there is no `ToAddress` method in BIP32 public key is because it doesn't make a lot of sense and that's why I removed it, by creating a different class for BIP44 public key that adds the `ToAddress` method.
In fact, the concept of "coin" is introduced by BIP44, where you have _coin_type_ in the derivation path allowing you to differentiate between different coins and therefore different address encodings. For this reason, the coin enums are defined in the Bip44 libraries (`Bip44Coins`, `Bip49Coins`, etc...) and you specify it in those classes constructor.
On the other side, BIP32 is completely generic and doesn't have any concept of "coin". It can derive any path for any elliptic curve. So, it's your job to encode the public key to the address format that you desire using the correct encoding class.

Regards,
Emanuele

**Comment by Anynomouss** [comment]
Hi Emanuele,

Thanks for clarifying and pointing to the relevant documentation. 
As you explain it indeed does not make much sense to have a generic ToAddress() function in Bip32.
Great library by the way.

Regards,

Anynomous
